// Polish toolbar: language toggle follows the text, Undo steps back through every version (server with MOCK_AI=1).
import { chromium } from '/home/claude/.npm-global/lib/node_modules/@playwright/mcp/node_modules/playwright/index.mjs';
import fs from 'node:fs';
const B = 'http://localhost:8890';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const call = async (method, p, body, c = '') => { const r = await fetch(B + p, { method, headers: { 'content-type': 'application/json', cookie: c }, body: body ? JSON.stringify(body) : undefined }); return { d: await r.json().catch(() => ({})), sc: r.headers.get('set-cookie') }; };
const ok = (c, m) => console.log(c ? 'PASS' : 'FAIL', m);
const lo = (await call('POST', '/api/login', { role: 'approver', name: 'Lior', password: 'lo' })).sc.split(';')[0];
const { d: { id } } = await call('POST', '/api/loans', { worksheet: JSON.parse(fs.readFileSync('test/purch.json')), inputs: { borrowerName: 'Sample Borrower', borrowerEmail: 'b@example.com' } }, lo);
const p = await (await b.newContext({ viewport: { width: 1300, height: 900 } })).newPage();
const errs = []; p.on('pageerror', (e) => errs.push(e.message));
await p.goto(B); await p.fill('input[name=name]', 'Lior'); await p.check('input[value=approver]'); await p.fill('input[name=password]', 'lo'); await p.click('button[type=submit]');
await p.waitForSelector('table.dash'); await p.goto(`${B}/#/loan/${id}`);
const ta = p.locator('textarea[name=noteToBorrower]'); await ta.waitFor();
const bar = ta.locator('xpath=following-sibling::div[contains(@class,"polish-bar")]');
const lang = bar.locator('.lang'), undo = bar.locator('.undo');
await ta.fill('These are the initial terms');
ok(await lang.textContent() === 'To Hebrew', 'English text offers "To Hebrew"');
await lang.click(); await p.waitForFunction(() => /[֐-׿]/.test(document.querySelector('textarea[name=noteToBorrower]').value));
ok(await lang.textContent() === 'To English', 'after translating, the button offers "To English"');
await bar.locator('[data-mode=shorter]').click(); await p.waitForFunction(() => document.querySelector('textarea[name=noteToBorrower]').value.startsWith('[shorter]'));
ok(await lang.textContent() === 'To English', 'still "To English" after another AI option');
ok(await undo.textContent() === 'Undo (2)', 'Undo shows 2 steps');
await lang.click(); await p.waitForFunction(() => document.querySelector('textarea[name=noteToBorrower]').value.startsWith('In English'));
ok(await lang.textContent() === 'To Hebrew', 'back to English, button offers "To Hebrew" again');
await undo.click(); await undo.click(); await undo.click();
ok(await ta.inputValue() === 'These are the initial terms', 'Undo steps all the way back to the original');
ok(await undo.isHidden(), 'Undo hides when nothing is left');
await ta.fill('אלה התנאים'); ok(await lang.textContent() === 'To English', 'typing Hebrew switches the button to "To English"');
ok(await ta.getAttribute('dir') === 'auto', 'Hebrew displays right-to-left');
ok(!errs.length, 'no page errors ' + errs.join(';'));
await b.close();
